logging.level.root=WARN
spring.main.allow-circular-references=true
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://viaduct.proxy.rlwy.net:32260/railway
spring.datasource.password=45Da43dAabG-B16g3G-1B4De3h3e442h
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.security.oauth2.client.registration.google.client-id=657482329976-jicagf9tslj0ij0bdgj3gdtkah4ikau3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email, profile
spring.security.oauth2.client.registration.facebook.client-id=800420772097840
spring.security.oauth2.client.registration.facebook.client-secret=c1893606896815eecf16b65e45616f30
spring.security.oauth2.client.registration.facebook.scope=email, public_profile
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html
spring.thymeleaf.cache=false
